<?php

namespace Proxies\__CG__\Psc\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class NavigationNode extends \Psc\Entities\NavigationNode implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function onPrePersist()
    {
        $this->__load();
        return parent::onPrePersist();
    }

    public function getContextLabel($context = 'default')
    {
        $this->__load();
        return parent::getContextLabel($context);
    }

    public function getEntityName()
    {
        $this->__load();
        return parent::getEntityName();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getIdentifier()
    {
        $this->__load();
        return parent::getIdentifier();
    }

    public function setIdentifier($id)
    {
        $this->__load();
        return parent::setIdentifier($id);
    }

    public function getI18nTitle()
    {
        $this->__load();
        return parent::getI18nTitle();
    }

    public function setI18nTitle(array $i18nTitle)
    {
        $this->__load();
        return parent::setI18nTitle($i18nTitle);
    }

    public function getTitle($lang)
    {
        $this->__load();
        return parent::getTitle($lang);
    }

    public function setTitle($value, $lang)
    {
        $this->__load();
        return parent::setTitle($value, $lang);
    }

    public function getI18nSlug()
    {
        $this->__load();
        return parent::getI18nSlug();
    }

    public function setI18nSlug(array $i18nSlug)
    {
        $this->__load();
        return parent::setI18nSlug($i18nSlug);
    }

    public function getSlug($lang)
    {
        $this->__load();
        return parent::getSlug($lang);
    }

    public function setSlug($value, $lang)
    {
        $this->__load();
        return parent::setSlug($value, $lang);
    }

    public function getLft()
    {
        $this->__load();
        return parent::getLft();
    }

    public function setLft($lft)
    {
        $this->__load();
        return parent::setLft($lft);
    }

    public function getRgt()
    {
        $this->__load();
        return parent::getRgt();
    }

    public function setRgt($rgt)
    {
        $this->__load();
        return parent::setRgt($rgt);
    }

    public function getDepth()
    {
        $this->__load();
        return parent::getDepth();
    }

    public function setDepth($depth)
    {
        $this->__load();
        return parent::setDepth($depth);
    }

    public function getImage()
    {
        $this->__load();
        return parent::getImage();
    }

    public function setImage($image)
    {
        $this->__load();
        return parent::setImage($image);
    }

    public function getCreated()
    {
        $this->__load();
        return parent::getCreated();
    }

    public function setCreated(\Webforge\Common\DateTime\DateTime $created)
    {
        $this->__load();
        return parent::setCreated($created);
    }

    public function getUpdated()
    {
        $this->__load();
        return parent::getUpdated();
    }

    public function setUpdated(\Webforge\Common\DateTime\DateTime $updated)
    {
        $this->__load();
        return parent::setUpdated($updated);
    }

    public function getContext()
    {
        $this->__load();
        return parent::getContext();
    }

    public function setContext($context)
    {
        $this->__load();
        return parent::setContext($context);
    }

    public function getPage()
    {
        $this->__load();
        return parent::getPage();
    }

    public function setPage(\Psc\Entities\Page $page = NULL)
    {
        $this->__load();
        return parent::setPage($page);
    }

    public function getChildren()
    {
        $this->__load();
        return parent::getChildren();
    }

    public function setChildren(\Doctrine\Common\Collections\Collection $children)
    {
        $this->__load();
        return parent::setChildren($children);
    }

    public function addChild(\Psc\Entities\NavigationNode $child)
    {
        $this->__load();
        return parent::addChild($child);
    }

    public function removeChild(\Psc\Entities\NavigationNode $child)
    {
        $this->__load();
        return parent::removeChild($child);
    }

    public function hasChild(\Psc\Entities\NavigationNode $child)
    {
        $this->__load();
        return parent::hasChild($child);
    }

    public function getParent()
    {
        $this->__load();
        return parent::getParent();
    }

    public function setParent(\Psc\Entities\NavigationNode $parent = NULL)
    {
        $this->__load();
        return parent::setParent($parent);
    }

    public function getContentStreams()
    {
        $this->__load();
        return parent::getContentStreams();
    }

    public function setContentStreams(\Doctrine\Common\Collections\Collection $contentStreams)
    {
        $this->__load();
        return parent::setContentStreams($contentStreams);
    }

    public function addContentStream(\Psc\Entities\ContentStream\ContentStream $contentStream)
    {
        $this->__load();
        return parent::addContentStream($contentStream);
    }

    public function removeContentStream(\Psc\Entities\ContentStream\ContentStream $contentStream)
    {
        $this->__load();
        return parent::removeContentStream($contentStream);
    }

    public function hasContentStream(\Psc\Entities\ContentStream\ContentStream $contentStream)
    {
        $this->__load();
        return parent::hasContentStream($contentStream);
    }

    public function getNodeHTML()
    {
        $this->__load();
        return parent::getNodeHTML();
    }

    public function equalsNode(\Webforge\CMS\Navigation\Node $other = NULL)
    {
        $this->__load();
        return parent::equalsNode($other);
    }

    public function generateSlugs()
    {
        $this->__load();
        return parent::generateSlugs();
    }

    public function getContentStream()
    {
        $this->__load();
        return parent::getContentStream();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getButtonRightIcon($context = 'default')
    {
        $this->__load();
        return parent::getButtonRightIcon($context);
    }

    public function getButtonLeftIcon($context = 'default')
    {
        $this->__load();
        return parent::getButtonLeftIcon($context);
    }

    public function export()
    {
        $this->__load();
        return parent::export();
    }

    public function equals(\Psc\Doctrine\Entity $otherEntity = NULL)
    {
        $this->__load();
        return parent::equals($otherEntity);
    }

    public function compareTo($other)
    {
        $this->__load();
        return parent::compareTo($other);
    }

    public function isNew()
    {
        $this->__load();
        return parent::isNew();
    }

    public function getEntityLabel()
    {
        $this->__load();
        return parent::getEntityLabel();
    }

    public function callSetter($field, $value)
    {
        $this->__load();
        return parent::callSetter($field, $value);
    }

    public function callGetter($field)
    {
        $this->__load();
        return parent::callGetter($field);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'titleDe', 'slugDe', 'lft', 'rgt', 'depth', 'image', 'created', 'updated', 'context', 'page', 'children', 'parent', 'contentStreams');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}